# Week:1 Introduction to Data Mining

### Objective:
The objective of the assignment is to understand how to install libraries, creating variables, calculate statistical metrics, basic python opreations, creating dataframes and basic pandas operations on the dataframe.

We have to use Fatal Police Shooting Data to answer the questions given in this notebook.

### Fatal Police Shooting Data

**About dataset**\
The dataset consists of following columns
1. **id**                         : unqiue identifier of each victim
2. **name**                       : name of a victim
3. **date**                       : date on fatal shooting 
4. **manner_of_death**            : manner of death classification
    * Shot
    * Shot and Tasered
5. **armed**                      : indicates that the victim was armed with some sort of implement that a police officer believed could inflict harm
    * undetermined: it is not known whether or not the victim had a weapon
    * unknown: the victim was armed, but it is not known what the object was
    * unarmed: the victim was not armed
6. **age**                        : age of victim
7. **gender**                     : the gender of the victim. The Post identifies victims by the gender they identify with if reports indicate that it differs from their biological sex.
    * M: Male
    * F: Female
    * None: Unknown
8. **race**                       : race of victim
    * W: White, non-Hispanic
    * B: Black, non-Hispanic
    * A: Asian
    * N: Native American
    * H: Hispanic
    * O: Other
    * None: unknown
9. **city**                       : the city where the fatal shooting took place. Note that in some cases this field may contain a county name if a more specific city is unavailable or unknown.
10. **state**                     : two-letter postal code abbreviation
11. **signs_of_mental_illness**   : News reports have indicated the victim had a history of mental health issues, expressed suicidal intentions or was experiencing mental distress at the time of the shooting.
12. **threat_level**              : These would include incidents where officers or others were shot at, threatened with a gun, attacked with other weapons or physical force, etc. The attack category is meant to flag the highest level of threat. The other and undetermined categories represent all remaining cases. Other includes many incidents where officers or others faced significant threats. 
13. **flee**                      : News reports have indicated the victim was moving away from officers
    * Foot
    * Car
    * Not fleeing
14. **body_camera**               : News reports have indicated an officer was wearing a body camera and it may have recorded some portion of the incident.

## Let's Begin

### Question: 1            (2 Marks)                                                                                                                                                  

Install the required libraries for the assignment

In [88]:
import numpy as np

<h4>Install a libray which help us to data injecting, data manipulation on the dataframe</h4>

In [89]:
pip install pandas

Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (2.2.0)
Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

<h5>
Comments:

    1. The Python Library thats is used for data injecting and data manipulation on the dataframe is Pandas
    2. We use pip command to install the 'pandas' library
    3. For the packages to be updated after installing the latest version you have to restart your kernel
</h5>

In [90]:
# Import the libary
import pandas as pd
#Check the version
print(pd.__version__)

2.2.0

<h4>
Upgrade the installed library to the latest version
</h4>

In [91]:
pip install pandas

Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (2.2.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy<2,>=1.23.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

<h5>
Comments:

    1. By using this command you will install the latest version of the pandas Library
    2. Alternatively, you can look up the latest version and use the command "pip install pandas==latest_version" like "pip install pandas=2.2.0"
    3. For the packages to be updated after installing the latest version you have to restart your kernel
</h5>

In [92]:
# Check the latest version after upgrading library
import pandas as pd
print(pd.__version__) # At the time of this assigment the latest version of the pandas library is 2.2.0
#Todo: Code to fill
 # 1. '<<__A__>>'--> import requried libraries
 # 2. '<<__B__>>'--> Check the version 
 # 3. '<<__C__>>'--> Updgrade the installed library to latest version
 # 4. '<<__D__>>'--> Check the latest version after upgrading library

2.2.0

### Question: 2 (2 marks)

- Fill in the missing code. 
- Store the data in to a variable, then display the top 5 and bottom 5 rows of records and check the dataset's shape.

In [93]:
# Load the dataframe and store it into the variable
df = pd.read_csv("fatal-police-shootings-data.csv")

In [94]:
# Display the Top 5 records
df.head()

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False

In [95]:
# Display the last 5 records
df.tail()

 #Todo: Code to fill
 # 1. '<<__A__>>'--> Appropriate pandas function to read the file == read_csv()
 # 2. '<<__B__>>'--> Appropriate path of the csv file == csv file_name if it is in the same folder as the python file if not file address need to be mentioned
 # 3. '<<__C__>>'--> Check for top 5 records using appropriate function = df.head()
 # 4. '<<__D__>>'--> Check for bottom 5 records using appropriate function = df.tail()

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera
4473,4907,Connor Betts,2019-08-04,shot,gun,24.0,M,W,Dayton,OH,True,attack,Not fleeing,False
4474,4909,Robert Clay Wilsford Jr.,2019-08-04,shot,gun,65.0,M,NaN,Hanceville,AL,True,attack,Not fleeing,False
4475,4910,TK TK,2019-08-05,shot,undetermined,NaN,NaN,NaN,Salt Lake City,UT,False,undetermined,Not fleeing,True
4476,4914,James Kirkwood,2019-08-05,shot,knife,49.0,M,B,Memphis,TN,False,attack,Foot,False
4477,4916,Marvin Alexis Urbina,2019-08-05,shot,vehicle,19.0,M,H,Bakersfield,CA,False,other,Car,False

In [96]:
# Check the shape of the datset
print("No of columns: ",df.shape[1])
print("No of rows: ",df.shape[0])

No of columns:  14
No of rows:  4478

### Question: 3 (2 marks)
Caluculate the statistical metrics of a column in a dataset

In [97]:
# Calculate the standard devaition
standard_deviation=df['age'].std()
print(standard_deviation)

13.067598403906874

In [98]:
# Average age of a victim
avg_age = round(df['age'].mean())
print(avg_age)

37

In [99]:
# Which city records the most Kill Events by police?

df['city'].value_counts()
# as you can see Phoenix and Los Angeles tie for the city with most Kill Events

city
Phoenix         68
Los Angeles     68
Houston         45
Las Vegas       40
San Antonio     36
                ..
Rome             1
Counce           1
Falls Church     1
Tukwila          1
Hanceville       1
Name: count, Length: 2168, dtype: int64

### Question: 4 (2 marks)
Create a new  " age categories " column using age column of a dataset

In [100]:
'''Hint: if age is between 0 to 12, then categorise as child. 
13-21 as Teenage, 22-34 as Youth, 35-50 as Adult, 51-120 as Senior citizens'''

    #-------- build the code down --------#
def create_age_cat(df):
    length = df.shape[0]
    for i in range(length):
        if df['age'][i]>=51 and df['age'][i]<=120:
            age_cat = 'Senior Citizen'
            df.loc[i, "age_categories"] = age_cat
        elif df['age'][i]<=50 and df['age'][i]>=35:
            age_cat = 'Adult'
            df.loc[i, "age_categories"] = age_cat
        elif df['age'][i]<=34 and df['age'][i]>=22:
            age_cat = 'Youth'
            df.loc[i, "age_categories"] = age_cat
        elif df['age'][i]<=21 and df['age'][i]>=13:
            age_cat = 'Teenage'
            df.loc[i, "age_categories"] = age_cat
        elif df['age'][i]<=12 and df['age'][i]>=0:
            age_cat = 'Child'
            df.loc[i, "age_categories"] = age_cat
    return df

In [101]:
df = create_age_cat(df)

In [102]:
df

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera,age_categories
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False,Senior Citizen
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False,Adult
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False,Youth
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False,Youth
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4473,4907,Connor Betts,2019-08-04,shot,gun,24.0,M,W,Dayton,OH,True,attack,Not fleeing,False,Youth
4474,4909,Robert Clay Wilsford Jr.,2019-08-04,shot,gun,65.0,M,NaN,Hanceville,AL,True,attack,Not fleeing,False,Senior Citizen
4475,4910,TK TK,2019-08-05,shot,undetermined,NaN,NaN,NaN,Salt Lake City,UT,False,undetermined,Not fleeing,True,NaN
4476,4914,James Kirkwood,2019-08-05,shot,knife,49.0,M,B,Memphis,TN,False,attack,Foot,False,Adult
4477,4916,Marvin Alexis Urbina,2019-08-05,shot,vehicle,19.0,M,H,Bakersfield,CA,False,other,Car,False,Teenage

In [103]:
# Display the first 5 records after creating the column
df.head()

#Todo: Code to fill
 # 1. Write code to build the conditions for the categories of age
 # 2. '<<__A__>>'--> method to display first 5 rows == df.head()

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera,age_categories
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,A,Shelton,WA,True,attack,Not fleeing,False,Senior Citizen
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,W,Aloha,OR,False,attack,Not fleeing,False,Adult
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,H,Wichita,KS,False,other,Not fleeing,False,Youth
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,W,San Francisco,CA,True,attack,Not fleeing,False,Youth
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,H,Evans,CO,False,attack,Not fleeing,False,Adult

### Question: 5 (2 marks)
Find the state which records the most kill events by police and display the type of attacks done on the male senior citizen of that state.

In [104]:
# Which State records the most Kill Events by police?
df['state'].value_counts()

# As you can see CA(california) has the most Kill Events

state
CA    680
TX    394
FL    279
AZ    220
CO    155
GA    146
OK    133
OH    131
WA    123
NC    121
TN    114
MO    109
IL     95
PA     94
LA     94
NM     90
AL     87
VA     82
IN     80
NV     78
KY     77
NY     76
MI     72
WI     71
OR     71
SC     69
MD     64
AR     64
NJ     58
MS     55
MN     54
UT     48
WV     48
KS     42
ID     32
AK     31
MA     30
IA     27
HI     26
MT     23
NE     20
ME     17
CT     16
SD     15
WY     13
NH     12
DC     12
DE     10
ND      9
VT      7
RI      4
Name: count, dtype: int64

In [105]:
# What kinds of attacks (armed) are most affected by the male senior citizens in the state of 'CA'
df[(df['age_categories'] == 'Senior Citizen') & (df['gender'] =="M") &  (df['state'] == "CA")]['armed'].value_counts()

#Todo: Code to fill

# 1. '<<__A__>>'--> write proper age category 
# 2. '<<__B__>>'--> write state filter 
# 3. '<<__C__>>'--> write the appropriate command to show distinct attacks without repetitions

armed
gun               32
knife             17
toy weapon         3
undetermined       2
unknown weapon     2
box cutter         1
unarmed            1
pipe               1
blunt object       1
pitchfork          1
metal pipe         1
Name: count, dtype: int64

In [106]:
# Save the processed data to use for Week2 assignment 
df.to_csv("week_1_assignment_output.csv",index=False)

## Thank you!